// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-ignore-label'
  | 'menu-manual-label'
  | 'menu-refresh-label'
  | 'menu-restore-label'
  | 'menu-root-label';
